apiVersion: v1
kind: Secret
metadata:
    name: postgres-neondb-owner-credentials
    namespace: database
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:eOgxi+oyp2IBYHtxCVIAGw==,iv:Hoko0DKfDQyy9Ce9VAGVsJgXJ+xt0xbcnQHXZu/1wcc=,tag:FolhWiwRxRdjgFIcO9eo6Q==,type:str]
    password: ENC[AES256_GCM,data:SOWSTA0YpW5aVjRatopOxBkIdprjA4Kf,iv:8K6cd+Ruq9ES9Y7CUqAueRVHhd7aCw1Oc8zB8y7TLko=,tag:nUJp7ts+P4zcICTtosGYaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYXFiU1ArZzNKdXdOTVpP
            NGNDNEQ4NHZCcXNWVWtnUENuY0lNeUFjekg4CmlJT0FnU1F4bUFhYmRFbzU3S0dS
            SEIySEJyZlVVMG5sYWpLS01UaXdGNHcKLS0tIHpqVG04TjcvdDhsc3ExTmVtY044
            R1BRcmZQZm9EYithT0NseDdjVHdQSWsKTGZe/GdKfwRcxBds0P2reA3KPs+eF735
            CPPBSmtdXIY+prHH3YYaMoSp5YQL+9YIVhnzMRWGwTI4u3j+poq6eg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T13:17:15Z"
    mac: ENC[AES256_GCM,data:SaNLrXeGKMuELWM/Y7XkFnvG2wV3Qx0HyXSpv+G6YSnOcbP/0PvRXSfMGjr65vtM7xS/Z5y8OSoL9qBIKXG1jR81SCizoJOCZxd3eM9W04sfKiKKcLEiTdPIeEMkrUQWGow/fD+3I3kU0HO5wklM/agSJm2dKD6+j6DptnxSYbo=,iv:qjCn2/LSTgc6bCRW3lCm6ygBAarIBTYFFABDwSqeZj0=,tag:LgghEtJjR5duimwa/BDLpw==,type:str]
    version: 3.13.1
