# Cloudflared tunnels.
#
# Why two tunnels:
# - `firefly`     — the in-cluster cloudflared DaemonSet (home k3s "firefly").
#                   Has routes into *.svc.cluster.local for the apps the home
#                   network actually hosts. THIS is what serves cc/cc-pro/
#                   atlantis/zoey/overseerr/radarr.
# - `firefly_oci` — cloudflared containers running on the OCI MikroTik CHRs
#                   (see terraform/oci/modules/mikrotik/). These can't reach
#                   the home cluster while the OCI<->home VPN is down, so they
#                   must NOT share the firefly tunnel — when they did, ~33%
#                   of incoming requests for any firefly host got load-
#                   balanced to the OCI side, where they 502'd on the
#                   unreachable upstreams (postmortem 2026-05-24).
#
# tunnel_secret is required by the resource but is only used at *creation*;
# importing an existing tunnel doesn't let us read the original secret back
# from the CF API. We supply a placeholder and ignore_changes so the import
# doesn't try to rotate. A genuine rotation (planned follow-up) would unset
# ignore_changes, set a real secret, and push the new credentials to wherever
# cloudflared reads them.

resource "cloudflare_zero_trust_tunnel_cloudflared" "firefly" {
  account_id = var.account_id
  name       = "firefly"

  # Placeholder; ignored after import. `secret` must be base64 of a 32+ byte
  # value but is only consumed at create-time. (Provider v4 renamed this from
  # tunnel_secret → secret somewhere along the line.)
  secret = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

  lifecycle {
    ignore_changes = [secret]
  }
}

# Random secret for firefly_oci. Generated by terraform on first apply,
# stored in state. The token (which is what cloudflared actually uses) is
# derived from {account_id, tunnel_id, secret} via the CF API data source
# below and exported for the runbook to copy into OCI Vault.
resource "random_password" "firefly_oci_tunnel_secret" {
  length  = 64
  special = false
}

resource "cloudflare_zero_trust_tunnel_cloudflared" "firefly_oci" {
  account_id = var.account_id
  name       = "firefly-oci"
  secret     = base64encode(random_password.firefly_oci_tunnel_secret.result)
}

# Minimal ingress for the OCI tunnel — a catch-all 404 only. The OCI MikroTik
# CHRs currently can't proxy anything useful (no working route to the home
# k3s cluster). Real routes get added here once the OCI<->home VPN is up and
# we decide what OCI-side traffic should funnel through this tunnel.
resource "cloudflare_zero_trust_tunnel_cloudflared_config" "firefly_oci" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.firefly_oci.id

  config {
    warp_routing {
      enabled = false
    }

    ingress_rule {
      service = "http_status:404"
    }
  }
}

# Tunnel connector token — the value cloudflared reads from $TUNNEL_TOKEN.
# Pulled via the API rather than constructed locally so we get whatever
# encoding CF currently uses (base64-of-JSON today, but historically has
# changed). Sensitive — written to terraform state, exposed via the output
# below, never logged.
data "cloudflare_zero_trust_tunnel_cloudflared_token" "firefly_oci" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.firefly_oci.id
}

output "firefly_oci_tunnel_id" {
  description = "Tunnel ID for firefly-oci. Needed for the cfargotunnel CNAME if/when OCI-side hostnames are added."
  value       = cloudflare_zero_trust_tunnel_cloudflared.firefly_oci.id
}

output "firefly_oci_tunnel_token" {
  description = "Connector token for firefly-oci. Copy into OCI Vault as `cloudflared-tunnel-token-firefly-oci`, then update terraform/oci/prod/eu-amsterdam-1/mikrotik/terragrunt.hcl with the resulting secret OCID. Fetch with: `terragrunt output -raw firefly_oci_tunnel_token`."
  value       = data.cloudflare_zero_trust_tunnel_cloudflared_token.firefly_oci.token
  sensitive   = true
}

# Ingress for the firefly tunnel. Mirrors the dashboard's current config:
# - overseerr.sargeant.co  -> http://overseerr.media.svc.cluster.local:5055
# - <anything else>        -> http_status:404
resource "cloudflare_zero_trust_tunnel_cloudflared_config" "firefly" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.firefly.id

  config {
    warp_routing {
      enabled = true
    }

    ingress_rule {
      hostname = "overseerr.sargeant.co"
      service  = "http://overseerr.media.svc.cluster.local:5055"
      origin_request {}
    }

    ingress_rule {
      hostname = "radarr.sargeant.co"
      service  = "http://radarr.media.svc.cluster.local:7878"
      origin_request {}
    }

    # GitHub webhooks → Atlantis (firefly cluster). This + the cloudflare
    # tunnel auto-creates the public CNAME atlantis.sargeant.co →
    # <tunnel-id>.cfargotunnel.com so the App's webhook URL resolves.
    ingress_rule {
      hostname = "atlantis.sargeant.co"
      service  = "http://atlantis.automation.svc.cluster.local:80"
      origin_request {}
    }

    # GitHub PR-review webhooks → comment-commander (firefly cluster).
    # Pairs with the explicit proxied CNAME in
    # terraform/cloudflare/dns-magmamoose/prod/terragrunt.hcl
    # (comment-commander.magmamoose.com → <tunnel-id>.cfargotunnel.com).
    # Same pattern as atlantis.sargeant.co / radarr.sargeant.co.
    ingress_rule {
      hostname = "comment-commander.magmamoose.com"
      service  = "http://comment-commander.comment-commander.svc.cluster.local:8000"
      origin_request {}
    }

    # comment-commander-pro dashboard (firefly cluster). Gated by the
    # self_hosted Cloudflare Access app in access_apps.tf (Caleb only —
    # the dashboard has no in-app auth/paywall yet). Pairs with the proxied
    # CNAME in dns-magmamoose/prod/terragrunt.hcl.
    ingress_rule {
      hostname = "comment-commander-pro.magmamoose.com"
      service  = "http://comment-commander-pro.comment-commander-pro.svc.cluster.local:8000"
      origin_request {}
    }

    # Zoey — project-intelligence dashboard (firefly cluster). Public so
    # Slack's interaction webhook can POST to /api/v1/slack/interaction;
    # the UI is gated by the Zoey Cloudflare Access app (access_apps.tf),
    # the /api/v1/slack/* path bypassed there. Pairs with the proxied
    # CNAME external-dns publishes from the k8s Ingress
    # (zoey repo: k8s/base/ingress.yaml → target=<firefly-tunnel>).
    #
    # Two rules: backend paths first (more specific), frontend catch-all
    # second. cloudflared evaluates ingress rules top-to-bottom.
    ingress_rule {
      hostname = "zoey.sargeant.co"
      path     = "^/(api|mcp|health)(/|$)"
      service  = "http://zoey-backend.zoey.svc.cluster.local:8000"
      origin_request {}
    }
    ingress_rule {
      hostname = "zoey.sargeant.co"
      service  = "http://zoey-frontend.zoey.svc.cluster.local:3000"
      origin_request {}
    }

    # Cloudflared requires the last rule to be a catch-all with no hostname.
    ingress_rule {
      service = "http_status:404"
    }
  }
}
