apiVersion: v1
kind: ConfigMap
metadata:
    name: homeassistant-config
    namespace: automation
data:
    configuration.yaml: ENC[AES256_GCM,data:JP9VR0ErNNLjeyrU9oZPgSlxRzFpJKrqtjFHo7tOBaS8EQXPsyUJMe95+Kl0DAIe1foM8FlPL7lxwH2uGJhZBUEAp84p7lErCEah2zosGLL8oLLd+CyULSjHF/lSvJ61RrtDXPQcXJce0eWSrJDXZH6Iz/+yVEzinv3heEdeor/hO9hW/Gk4PyxfzP+I+clUUGVCnxpED0RNW85Z7x3kkc/Venm1gi2x2NIlVCnH5h8N07smrxw4JmyfoXyB0xdS0eyLVs3bLZvkQawujOs8H5ktZykyd03zF4hOlEpxzbel4t7Y7A9RWRoJNK5Ku9x3bLSAJTAvc0JtWlJ2lIpSFI2x3X/UnbI6rgpyetnpw7Zstb7ieMEzD8nejJcwAHfy2p+cm4OonG2YtleMJcWEBdocB1e1lkP4rYnSvhqVbUMyUBqSJ7Popoi4ARic6nUToMTlUw3va8lwhR9p94wMg9yXDLbArZQrUNnQA4R2r3y6ZqygAJ3lP/rWZfFROQxafDoKYsF+b0KJ1VNOpjGrNoGe1SyscjhKEVpRZH4M6F7VznSrRvGyYFgtsA9648P5xlfVTv9pOEV3JotaORxS7dQFC4U1K+KDmgLyBcYFULZ+KkQwOhQi/qA6ea+wXzgI+wd6lri273esWiLppISocBPo1ujA9/nsWKVn9Ee8V9LoPwCx4n4+AObgtrR1O+205l7Sy7LMB/Z0ssD3PVYpQZYAtMY98MiWfDzBXKDSI/e2jT5Bbg3nL7Zj4IQ0B1T48U43VNfbNtaB3PbJ/5X6ZAB6R568h13sE4RmOXVMjWO5ZtPbdOe45kendgZZb6+SgHhUzuxPwQjs1wRNYqNf6gMG0h3Fv/AmGkKsT+56ZrYWwrkCD5ptilGJyhEpgETmcPC2HRFgjeiHTzc1jW6EWLjI+/rrN08S1uhggCuuxosRx4rrOuP+k5oEZfw=,iv:PKBeHDx3gifJZPoECFbdV+LsjCd7b6Bxn/eu+qVIPwI=,tag:htreBq3QyYbZpUSi12jZtw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdm5tNWpITXk3WFhvZ1N4
            NUZ1S1NnaFFoWWVDV2FkamRhVWgrK1RlOGp3CkE2MVFCU0U2TDVPc2tFaGY1dGhx
            aFZlUmIwNXZ0anFTenU0aWlXQVVKeU0KLS0tIHRWQ0NiRFM5YThKdnJaSStkQUdr
            YnhCNy8wcldtUjB0RGMvMXBpODMwV2MKHUXOp+gCBiKFzkcCXsfImItne3H6FYh+
            69jNZaxYlHLkXhpIlZcostHBCDsbsvJtV3lMB670YAQoNzBhgg80mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T09:46:55Z"
    mac: ENC[AES256_GCM,data:iJ9iHz6uB6vVQQeJ8REjH348izW6oMU82HvXGoZElmdKLn9V8l7xM8JoIq+wlIL4WAiL7x118rbOX6/WLhhPYS50nwfpzZCnTJaJgZYnPNcBsPkbGwrL3nz20yZfoLHBCnbBnmF36UWXWXZ4KnbfuO+36Cb+RhztX+2gV8ksRa0=,iv:t3aZD9kOg8hwluxsgcAkelXQdJalsYWi7XVzAoY6pOo=,tag:eQGQBlqD0S3BAZXgKnLccg==,type:str]
    version: 3.13.1
