apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
components:
  - ../../../../_components/wireguard-sidecar
  - ../../../../_components/resource-profiles/c.micro
  - ../../../../_components/node-selectors/mini
patches:
  - target:
      kind: Deployment
      name: nzbhydra2
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/secret/secretName
        value: nzbhydra2-wireguard
