apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - pv.yaml
components:
  - ../../../../components/wireguard-sidecar
  - ../../../../components/resource-profiles/c.micro
  - ../../../../components/node-selectors/mini
patches:
  - target:
      kind: StatefulSet
      name: qbittorrent
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/secret/secretName
        value: qbittorrent-wireguard
