apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - pv.yaml
  - privado-credentials.enc.yaml
components:
  - ../../../../components/gluetun-sidecar
  - ../../../../components/resource-profiles/c.micro
  - ../../../../components/node-selectors/mini
