apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - pv.yaml
  - configmap.yaml
components:
  - ../../../../components/wireguard-sidecar
  - ../../../../components/resource-profiles/c.pico
  - ../../../../components/node-selectors/mini
patches:
  - target:
      kind: Deployment
      name: prowlarr
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/secret/secretName
        value: prowlarr-wireguard
