---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-trivy-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/trivy-operator/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
