apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../_base/security/namespace.yaml
  # kubescape, gatekeeper migrated to kubernetes/apps/<app>/
  # owned by Kustomization/flux-system/prod-<app>
