apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # automation
  - ./atlantis
  - ./homeassistant
  - ./homebridge
  - ./mikrotik-minder
  - ./n8n
  # backup
  - ./timemachine
  # miscellaneous (dashboard)
  - ./headlamp
  # media
  - ./bazarr
  - ./flaresolverr
  - ./jackett
  - ./nzbhydra2
  - ./overseerr
  - ./plex
  - ./prowlarr
  - ./qbittorrent
  - ./radarr
  - ./sabnzbd
  - ./sonarr
  # miscellaneous
  - ./excalidraw
  - ./nextcloud
  - ./syncthing
  - ./wordpress
  # observability
  - ./blackbox-exporter
  - ./fluent-bit
  - ./krr
  - ./kube-prometheus-stack
  - ./loki
  - ./thanos-compactor
  - ./thanos-query
  - ./thanos-store
  # security
  - ./gatekeeper
  - ./kubescape
